---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-514febb6f630> in <module>()
     78 # train the model
     79 model_scratch = train(2, loaders_scratch, model_scratch, optimizer_scratch, 
---> 80                       criterion_scratch, use_cuda, 'model_scratch.pt')
     81 
     82 # load the model that got the best validation accuracy

<ipython-input-16-514febb6f630> in train(n_epochs, loaders, model, optimizer, criterion, use_cuda, save_path)
     25 
     26             # forwarward pass
---> 27             output = model(data)
     28 
     29             # calculate batch loss

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

<ipython-input-14-4eef0efeae9b> in forward(self, x)
     24         ## Define forward behavior
     25         x = self.pool(F.relu(self.conv1(x)))
---> 26         x = self.pool(F.relu(self.conv2(x)))
     27         x = self.pool(F.relu(self.conv3(x)))
     28         x = self.pool(F.relu(self.conv4(x)))

/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py in relu(input, inplace)
    617     if inplace:
    618         return torch.relu_(input)
--> 619     return torch.relu(input)
    620 
    621 

RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/THC/generic/THCStorage.cu:58